// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bL85eZ75LB8weu7MMcTF7o31y6XSj0Q',
    appId: '1:1069168519679:web:2c913dc4ef41bffcfd5fca',
    messagingSenderId: '1069168519679',
    projectId: 'wewish-b573a',
    authDomain: 'wewish-b573a.firebaseapp.com',
    storageBucket: 'wewish-b573a.appspot.com',
    measurementId: 'G-FKRH36NVGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH1sfHZ5o1448EtbVu-c7IroStmlyvOGU',
    appId: '1:1069168519679:android:faf61e0bfbe0b50ffd5fca',
    messagingSenderId: '1069168519679',
    projectId: 'wewish-b573a',
    storageBucket: 'wewish-b573a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC525qVzEbU-VfIIgsh1eNRKX9J3nze0hs',
    appId: '1:1069168519679:ios:095c16d8ed17591bfd5fca',
    messagingSenderId: '1069168519679',
    projectId: 'wewish-b573a',
    storageBucket: 'wewish-b573a.appspot.com',
    iosClientId: '1069168519679-50pfur68onsjplmoihsstmif4ukua63s.apps.googleusercontent.com',
    iosBundleId: 'com.codeinsongdo.wewish.wewish',
  );
}
